stages:
- prepare
- check
- xxxxx
- build
- test

.template: &env-info
  before_script:
  - hostname && hostname -I
  - env | grep -e CI_COMMIT -e CI_PIPELINE

.template: &only-protected
  only:
    variables:
    - $CI_COMMIT_REF_PROTECTED == "true"

.template: &only-unprotected
  only:
    variables:
    - $CI_COMMIT_REF_PROTECTED == "false"

build-base:
  <<: *env-info
  stage: prepare
  tags:
  - normal
  script:
  - ./docker.local/bin/build.base.sh

unit-tests:
  <<: *env-info
  stage: check
  allow_failure: true
  tags:
  - normal
  script:
  - ./docker.local/bin/unit_test.sh --ci
